name: Build Tweego Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Tweego
        run: |
          wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip

      - name: Unzip Tweego
        run: |
          unzip tweego-2.1.1-linux-x64.zip -d tweego

      - name: Run Tweego
        run: |
          ./tweego/tweego -o index.html --module=scripts.js --module=std.css --no--trim src

      - name: Gather artifacts
        run: |
          mv index.html $GITHUB_WORKSPACE/index.html
          mv std.css $GITHUB_WORKSPACE/std.css || true
          mv scripts.js $GITHUB_WORKSPACE/scripts.js || true
          mv music $GITHUB_WORKSPACE/music || true

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tweego-output
          path: |
            $GITHUB_WORKSPACE/index.html
            $GITHUB_WORKSPACE/std.css
            $GITHUB_WORKSPACE/scripts.js
            $GITHUB_WORKSPACE/music

      # upload to github.io
      #- name: Deploy to GitHub Pages
      #uses: peaceiris/actions-gh-pages@v3
      #with:
      #github_token: ${{ secrets.GITHUB_TOKEN }}
      #publish_dir: $GITHUB_WORKSPACE
      #publish_branch: gh-pages
      #cname: ${{ secrets.CNAME }}
      #commit_message: ${{ github.event.head_commit.message }}
