name: Build Tweego Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: build game
        run: |
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
      - name: Run Tweego
        run: |
          ./tweego -o dist/index.html --no--trim src

      - name: Gather artifacts (may not be necessary)
        run: |
          mv std.css ./dist/std.css || true
          mv scripts.js ./dist/scripts.js || true
          mv music ./dist/music || true

      # upload to github.io
      #- name: Deploy to GitHub Pages
      #uses: peaceiris/actions-gh-pages@v3
      #with:
      #github_token: ${{ secrets.GITHUB_TOKEN }}
      #publish_dir: ./dist
      #publish_branch: gh-pages
